/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssignmentDetails: typeof import('./src/components/AssignmentDetails.vue')['default']
    AssignmentsList: typeof import('./src/components/AssignmentsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VaAccordion: typeof import('vuestic-ui')['VaAccordion']
    VaAlert: typeof import('vuestic-ui')['VaAlert']
    VaAvatar: typeof import('vuestic-ui')['VaAvatar']
    VaButton: typeof import('vuestic-ui')['VaButton']
    VaCard: typeof import('vuestic-ui')['VaCard']
    VaCardActions: typeof import('vuestic-ui')['VaCardActions']
    VaCardContent: typeof import('vuestic-ui')['VaCardContent']
    VaCardTitle: typeof import('vuestic-ui')['VaCardTitle']
    VaCheckbox: typeof import('vuestic-ui')['VaCheckbox']
    VaCollapse: typeof import('vuestic-ui')['VaCollapse']
    VaCounter: typeof import('vuestic-ui')['VaCounter']
    VaDivider: typeof import('vuestic-ui')['VaDivider']
    VaForm: typeof import('vuestic-ui')['VaForm']
    VaIcon: typeof import('vuestic-ui')['VaIcon']
    VaInnerLoading: typeof import('vuestic-ui')['VaInnerLoading']
    VaInput: typeof import('vuestic-ui')['VaInput']
    VaLayout: typeof import('vuestic-ui')['VaLayout']
    VaList: typeof import('vuestic-ui')['VaList']
    VaListItem: typeof import('vuestic-ui')['VaListItem']
    VaListItemLabel: typeof import('vuestic-ui')['VaListItemLabel']
    VaListItemSection: typeof import('vuestic-ui')['VaListItemSection']
    VaListLabel: typeof import('vuestic-ui')['VaListLabel']
    VaListSeparator: typeof import('vuestic-ui')['VaListSeparator']
    VaNavbar: typeof import('vuestic-ui')['VaNavbar']
    VaNavbarItem: typeof import('vuestic-ui')['VaNavbarItem']
    VaPagination: typeof import('vuestic-ui')['VaPagination']
    VaPopover: typeof import('vuestic-ui')['VaPopover']
    VaProgressBar: typeof import('vuestic-ui')['VaProgressBar']
    VaScrollContainer: typeof import('vuestic-ui')['VaScrollContainer']
    VaSelect: typeof import('vuestic-ui')['VaSelect']
    VaSidebar: typeof import('vuestic-ui')['VaSidebar']
    VaSidebarItem: typeof import('vuestic-ui')['VaSidebarItem']
    VaSidebarItemContent: typeof import('vuestic-ui')['VaSidebarItemContent']
    VaSidebarItemTitle: typeof import('vuestic-ui')['VaSidebarItemTitle']
    VaSkeleton: typeof import('vuestic-ui')['VaSkeleton']
    VaSkeletonGroup: typeof import('vuestic-ui')['VaSkeletonGroup']
    VaValue: typeof import('vuestic-ui')['VaValue']
    Vue: typeof import('./src/components/Vue.vue')['default']
    VuesticToast: typeof import('./src/components/VuesticToast.vue')['default']
  }
}
